const skills = [
  {
    name: "React JS",
    niveau: "Maitrise",
    niveauCSS: "vert",
    description: "",
    icon: "https://img.icons8.com/?size=100&id=bzf0DqjXFHIW&format=png&color=000000",
    categorie: "Technos",
  },
  {
    name: "NodeJS",
    niveau: "En Cour",
    niveauCSS: "vert",
    description: "",
    icon: "https://img.icons8.com/?size=100&id=hsPbhkOH4FMe&format=png&color=000000",
    categorie: "Technos",
  },
  {
    name: "MySQL",
    niveau: "En Cour",
    niveauCSS: "orange",
    description: "",
    icon: "https://img.icons8.com/?size=100&id=13406&format=png&color=000000",
    categorie: "Technos",
  },
  {
    name: "JavaScript",
    niveau: "Maitrise",
    niveauCSS: "vert",
    description: "",
    icon: "https://img.icons8.com/?size=100&id=108784&format=png&color=000000",
    categorie: "Technos",
  },
  {
    name: "CSS3/SASS",
    niveau: "Maitrise",
    niveauCSS: "vert",
    description: "",
    icon: "https://img.icons8.com/?size=100&id=QBqFNfPPB2Kx&format=png&color=000000",
    categorie: "Technos",
  },
  {
    name: "HTML",
    niveau: "Maitrise",
    niveauCSS: "vert",
    description: "",
    icon: "https://img.icons8.com/?size=100&id=20909&format=png&color=000000",
    categorie: "Technos",
  },

  {
    name: "Python",
    niveau: "Passion",
    niveauCSS: "doree",
    description: "",
    icon: "https://img.icons8.com/?size=100&id=13441&format=png&color=000000",
    categorie: "AutresTechnos",
  },
  {
    name: "Express",
    niveau: "En Cour",
    niveauCSS: "orange",
    description: "",
    icon: "https://img.icons8.com/?size=100&id=SDVmtZ6VBGXt&format=png&color=000000",
    categorie: "AutresTechnos",
  },
  {
    name: "react modules",
    niveau: "Maitrise",
    niveauCSS: "vert",
    description: "",
    icon: "https://img.icons8.com/?size=100&id=V7bWlRbkNWas&format=png&color=000000",
    categorie: "AutresTechnos",
  },
  {
    name: "Vites",
    niveau: "Maitrise",
    niveauCSS: "vert",
    description: "",
    icon: "https://img.icons8.com/?size=100&id=13686&format=png&color=000000",
    categorie: "AutresTechnos",
  },
  {
    name: "Npm",
    niveau: "Maitrise",
    niveauCSS: "vert",
    description: "",
    icon: "https://img.icons8.com/?size=100&id=24895&format=png&color=000000",
    categorie: "AutresTechnos",
  },
  {
    name: "Github / Git",
    niveau: "Maitrise",
    niveauCSS: "vert",
    description: "",
    icon: "https://img.icons8.com/?size=100&id=63777&format=png&color=000000",
    categorie: "AutresTechnos",
  },
  {
    name: "Figma",
    niveau: "En Cour",
    niveauCSS: "orange",
    description: "",
    icon: "https://img.icons8.com/?size=100&id=8gfeOoqrHqJU&format=png&color=000000",
    categorie: "Logiciels",
  },
  {
    name: "Canvas",
    niveau: "En Cour",
    niveauCSS: "orange",
    description: "",
    icon: "https://img.icons8.com/?size=100&id=b05cg06kp3yX&format=png&color=000000",
    categorie: "Logiciels",
  },
  {
    name: "Anglais",
    niveau: "Maitrise",
    niveauCSS: "vert",
    description: "",
    icon: "https://img.icons8.com/?size=100&id=xapj7ZzAUZKI&format=png&color=000000",
    categorie: "Langues",
  },
  {
    name: "Espagnol",
    niveau: "Debut d'aprentissage",
    niveauCSS: "rouge",
    description: "",
    icon: "https://img.icons8.com/?size=100&id=ZGEFKpJoPdJQ&format=png&color=000000",
    categorie: "Langues",
  },
  {
    name: "Raspberry",
    niveau: "Maitrise",
    niveauCSS: "vert",
    description: "",
    icon: "https://img.icons8.com/?size=100&id=19529&format=png&color=000000",
    categorie: "InteretPerso",
  },
  {
    name: "Arduino",
    niveau: "Maitrise",
    niveauCSS: "vert",
    description: "",
    icon: "https://img.icons8.com/?size=100&id=13444&format=png&color=000000",
    categorie: "InteretPerso",
  },
  {
    name: "Electronique",
    niveau: "En cour",
    niveauCSS: "orange",
    description: "",
    icon: "https://img.icons8.com/?size=100&id=q9uNkwmkxLfN&format=png&color=000000",
    categorie: "InteretPerso",
  },
];

export default skills;
